language: cpp
dist: bionic

addons:
    apt:
        packages:
            - libhdf5-serial-dev

matrix:
    include:
        - name: "Python 3.6.7 on Xenial Linux"
          os: linux
          env: PYTHON=3.6

        - name: "Python 3.7.4 on macOS"
          os: osx
          osx_image: xcode10.2
          language: generic
          env: PYTHON=3.7

cache: 
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/hdf5
        - $HOME/.ccache

before_install:
- |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update; brew install python3
        pip3 install virtualenv
        python3 -m virtualenv venv
    else
        pip install --user --upgrade pip virtualenv
        virtualenv -p python$PYTHON venv
    fi
    source venv/bin/activate
    which python
    python --version
    pip install numpy
install:
- pip install ".[test]" --verbose -e .
script:
- pytest

after_success:
    - codecov
