language: cpp
dist: focal

addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - gfortran

matrix:
    include:
        - name: "Xenial Linux"
          os: linux

        - name: "macOS xcode10.2"
          os: osx
          osx_image: xcode10.2

cache: 
    directories:
        - $HOME/.ccache
        - $HOME/.local/bin
        - $HOME/.local/lib
        - $HOME/.local/include

before_install:
    ############################################################################
    # All the dependencies are installed in ${HOME}/deps/
    ############################################################################
    - DEPS_DIR="${HOME}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    
    ############################################################################
    # Install a recent CMake
    ############################################################################
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.16/cmake-3.16.0-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      else
        brew install cmake || brew upgrade cmake
      fi
    - cmake --version

    #############################################################################
    # Return to root directory of the project
    #############################################################################
    - cd -
    - pwd

install:
    - mkdir build && cd build && cmake .. -DENABLE_TESTING=ON
    - make -j8

script:
    - ./test/nuchic-testsuite
    - ./test/nuchic-fortran-testsuite
