language: python
python:
    - "3.6"
cache: pip
sudo: required
before_install:
    - sudo apt-get install gfortran
install:
    - pip install -r requirements.txt
    - pip install lhapdf
    - python setup.py install
script:
    - py.test --cov-report term-missing --cov nuChic -v
