language: python
dist: bionic
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
cache: pip
sudo: required
before_install:
    - sudo apt-get install gfortran
    - pip install -r requirements.txt
    - pip install -U pip
    - pip install -U pytest
    - pip install lhapdf
    - pip install codecov
install:
    - pip install ".[test]" .
script:
    - pytest
after_success:
    - codecov
