language: python
matrix:
    include:
        - name: "Python 3.5.6 on Xenial Linux"
          python: 3.5
          sudo: required
          before_install:
              - sudo apt-get install gfortran

        - name: "Python 3.6.7 on Xenial Linux"
          python: 3.6
          sudo: required
          before_install:
              - sudo apt-get install gfortran

        - name: "Python 3.7.1 on Xenial Linux"
          python: 3.7
          sudo: required
          before_install:
              - sudo apt-get install gfortran

        - name: "Python 3.7.4 on macOS"
          os: osx
          osx_image: xcode11
          language: shell
          before_install:
              - pip3 install mock

# Ignore building on Windows for now
#        - name: "Python 3.7.4 on Windows"
#          os: windows
#          language: shell
#          before_install:
#              - choco install python
#              - python -m pip install --upgrade pip
#              - pip3 install numpy
#          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

cache: pip # Cache pip dependencies
before_install:
    - pip3 install -U pip
    - pip3 install -U pytest
    - pip3 install codecov
install:
    - pip3 install ".[test]" .
script:
    - pytest
    - nuchic --testing
after_success:
    - codecov
