language: cpp
dist: bionic

addons:
    apt:
        packages:
            - libhdf5-serial-dev

matrix:
    include:
        - name: "Python 3.6.7 on Xenial Linux"
          os: linux
          env: PYTHON=3.6

        - name: "Python 3.7.1 on Xenial Linux"
          os: linux
          env: PYTHON=3.7

        - name: "Python 3.7.4 on macOS"
          os: osx
          env: PYTHON=3.7

cache: 
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/hdf5
        - $HOME/.ccache

before_install:
- |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
    pip install numpy
install:
- |
    python setup.py sdist
    pip install ".[test]" --verbose dist/*.tar.gz
script:
- pytest

after_success:
    - codecov
