language: cpp
dist: bionic
matrix:
    include:
        - name: "Python 3.5.6 on Xenial Linux"
          os: linux
          env: PYTHON=3.5

        - name: "Python 3.6.7 on Xenial Linux"
          os: linux
          env: PYTHON=3.6

        - name: "Python 3.7.1 on Xenial Linux"
          os: linux
          env: PYTHON=3.7

        - name: "Python 3.7.4 on macOS"
          os: osx
          env: PYTHON=3.7

cache: pip # Cache pip dependencies
before_install:
- |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-8 CC=gcc-8; fi
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update; brew install python3;
    fi
    pip install --user --upgrade pip virtualenv
    virtualenv -p python$PYTHON venv
    source venv/bin/activate
install:
- |
    python setup.py sdist
    pip install ".[test]" --verbose dist/*.tar.gz
script:
- pytest

after_success:
    - codecov
