[build-system]
requires = ["scikit-build-core>=0.5"]
build-backend = "scikit_build_core.build"

[project]
name = "Achilles"
version = "0.3.0"

[tool.scikit-build]
cmake.args = ["-DCMAKE_POLICY_VERSION_MINIMUM=3.5", "-DACHILLES_ENABLE_PYTHON=ON"]
cmake.source-dir = "."
sdist.include = ["data/**", "flux/**"]
