!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitxsec(f2pysetupfunc)
      use xsec, only : xmp
      use xsec, only : xmn
      use xsec, only : xm
      use xsec, only : hbarc
      use xsec, only : g_f
      use xsec, only : pi
      use xsec, only : c0
      use xsec, only : e
      use xsec, only : ef
      use xsec, only : cost
      use xsec, only : q2
      use xsec, only : p2
      use xsec, only : pf2
      use xsec, only : sint
      use xsec, only : sina2
      use xsec, only : wf
      use xsec, only : wtf
      external f2pysetupfunc
      call f2pysetupfunc(xmp,xmn,xm,hbarc,g_f,pi,c0,e,ef,cost,q2,p2,pf2,&
     &sint,sina2,wf,wtf)
      end subroutine f2pyinitxsec

      
      subroutine f2pyinitdirac_matrices(f2pysetupfunc)
      use dirac_matrices, only : dirac_matrices_in
      use dirac_matrices, only : define_spinors
      use dirac_matrices, only : current_init
      use dirac_matrices, only : det_ja
      use dirac_matrices, only : det_res1b
      external f2pysetupfunc
      call f2pysetupfunc(dirac_matrices_in,define_spinors,current_init,d&
     &et_ja,det_res1b)
      end subroutine f2pyinitdirac_matrices


