name: Feature Request
description: Request a feature be added
title: "[Feature]: "
labels: ["feature"]
assignees:
  - jxi24
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        If you have issues with the code, see either the bug report or the compilation report.
        This report is for asking for new features or options to be added.
  - type: textarea
    id: request
    attributes:
      label: What would you like to see added?
      description: Please be as detailed as possible.
      placeholder: Feature description
      value: "I would like..."
    validations:
      required: true
