blank_issues_enabled: false
contact_links:
  - name: Achilles discussions
    url: https://github.com/AchillesGen/Achilles/discussions
    about: Please ask and answer questions here. This is the place for finding FAQ, common issues with setup, etc.
