# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_GeantPPData')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_GeantPPData')
    _GeantPPData = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GeantPPData', [dirname(__file__)])
        except ImportError:
            import _GeantPPData
            return _GeantPPData
        try:
            _mod = imp.load_module('_GeantPPData', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _GeantPPData = swig_import_helper()
    del swig_import_helper
else:
    import _GeantPPData
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _GeantPPData.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _GeantPPData.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _GeantPPData.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _GeantPPData.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _GeantPPData.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _GeantPPData.SwigPyIterator_equal(self, x)

    def copy(self):
        return _GeantPPData.SwigPyIterator_copy(self)

    def next(self):
        return _GeantPPData.SwigPyIterator_next(self)

    def __next__(self):
        return _GeantPPData.SwigPyIterator___next__(self)

    def previous(self):
        return _GeantPPData.SwigPyIterator_previous(self)

    def advance(self, n):
        return _GeantPPData.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _GeantPPData.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _GeantPPData.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _GeantPPData.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _GeantPPData.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _GeantPPData.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _GeantPPData.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _GeantPPData.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _GeantPPData.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _GeantPPData.vectord___nonzero__(self)

    def __bool__(self):
        return _GeantPPData.vectord___bool__(self)

    def __len__(self):
        return _GeantPPData.vectord___len__(self)

    def __getslice__(self, i, j):
        return _GeantPPData.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _GeantPPData.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _GeantPPData.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _GeantPPData.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _GeantPPData.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _GeantPPData.vectord___setitem__(self, *args)

    def pop(self):
        return _GeantPPData.vectord_pop(self)

    def append(self, x):
        return _GeantPPData.vectord_append(self, x)

    def empty(self):
        return _GeantPPData.vectord_empty(self)

    def size(self):
        return _GeantPPData.vectord_size(self)

    def swap(self, v):
        return _GeantPPData.vectord_swap(self, v)

    def begin(self):
        return _GeantPPData.vectord_begin(self)

    def end(self):
        return _GeantPPData.vectord_end(self)

    def rbegin(self):
        return _GeantPPData.vectord_rbegin(self)

    def rend(self):
        return _GeantPPData.vectord_rend(self)

    def clear(self):
        return _GeantPPData.vectord_clear(self)

    def get_allocator(self):
        return _GeantPPData.vectord_get_allocator(self)

    def pop_back(self):
        return _GeantPPData.vectord_pop_back(self)

    def erase(self, *args):
        return _GeantPPData.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _GeantPPData.new_vectord(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _GeantPPData.vectord_push_back(self, x)

    def front(self):
        return _GeantPPData.vectord_front(self)

    def back(self):
        return _GeantPPData.vectord_back(self)

    def assign(self, n, x):
        return _GeantPPData.vectord_assign(self, n, x)

    def resize(self, *args):
        return _GeantPPData.vectord_resize(self, *args)

    def insert(self, *args):
        return _GeantPPData.vectord_insert(self, *args)

    def reserve(self, n):
        return _GeantPPData.vectord_reserve(self, n)

    def capacity(self):
        return _GeantPPData.vectord_capacity(self)
    __swig_destroy__ = _GeantPPData.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _GeantPPData.vectord_swigregister
vectord_swigregister(vectord)

class vectordd(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectordd, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectordd, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _GeantPPData.vectordd_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _GeantPPData.vectordd___nonzero__(self)

    def __bool__(self):
        return _GeantPPData.vectordd___bool__(self)

    def __len__(self):
        return _GeantPPData.vectordd___len__(self)

    def __getslice__(self, i, j):
        return _GeantPPData.vectordd___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _GeantPPData.vectordd___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _GeantPPData.vectordd___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _GeantPPData.vectordd___delitem__(self, *args)

    def __getitem__(self, *args):
        return _GeantPPData.vectordd___getitem__(self, *args)

    def __setitem__(self, *args):
        return _GeantPPData.vectordd___setitem__(self, *args)

    def pop(self):
        return _GeantPPData.vectordd_pop(self)

    def append(self, x):
        return _GeantPPData.vectordd_append(self, x)

    def empty(self):
        return _GeantPPData.vectordd_empty(self)

    def size(self):
        return _GeantPPData.vectordd_size(self)

    def swap(self, v):
        return _GeantPPData.vectordd_swap(self, v)

    def begin(self):
        return _GeantPPData.vectordd_begin(self)

    def end(self):
        return _GeantPPData.vectordd_end(self)

    def rbegin(self):
        return _GeantPPData.vectordd_rbegin(self)

    def rend(self):
        return _GeantPPData.vectordd_rend(self)

    def clear(self):
        return _GeantPPData.vectordd_clear(self)

    def get_allocator(self):
        return _GeantPPData.vectordd_get_allocator(self)

    def pop_back(self):
        return _GeantPPData.vectordd_pop_back(self)

    def erase(self, *args):
        return _GeantPPData.vectordd_erase(self, *args)

    def __init__(self, *args):
        this = _GeantPPData.new_vectordd(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _GeantPPData.vectordd_push_back(self, x)

    def front(self):
        return _GeantPPData.vectordd_front(self)

    def back(self):
        return _GeantPPData.vectordd_back(self)

    def assign(self, n, x):
        return _GeantPPData.vectordd_assign(self, n, x)

    def resize(self, *args):
        return _GeantPPData.vectordd_resize(self, *args)

    def insert(self, *args):
        return _GeantPPData.vectordd_insert(self, *args)

    def reserve(self, n):
        return _GeantPPData.vectordd_reserve(self, n)

    def capacity(self):
        return _GeantPPData.vectordd_capacity(self)
    __swig_destroy__ = _GeantPPData.delete_vectordd
    __del__ = lambda self: None
vectordd_swigregister = _GeantPPData.vectordd_swigregister
vectordd_swigregister(vectordd)

class G4LEpp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, G4LEpp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, G4LEpp, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _GeantPPData.new_G4LEpp()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _GeantPPData.delete_G4LEpp
    __del__ = lambda self: None
G4LEpp_swigregister = _GeantPPData.G4LEpp_swigregister
G4LEpp_swigregister(G4LEpp)

# This file is compatible with both classic and new-style classes.


