name: Create Docker image on push to dev, main, or releases

on:
  push:
    branches:
      - "dev"
      - "main"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
