name: CMake Build/Test/Check

on: [push, pull_request]

jobs:
  ci:
    name: Job
    uses: ./.github/workflows/cmake.yml
    with:
      matrix: >
          {
            "include": [
              {
                "name": "Ubuntu GCC",
                "os": "ubuntu-latest",
                "cc": "gcc",
                "cxx": "g++",
                "fort": "gfortran",
                "coverage": true
              },
              {
                "name": "Ubuntu Clang",
                "os": "ubuntu-latest", 
                "cc": "clang",
                "cxx": "clang++",
                "fort": "gfortran",
                "coverage": false
              },
              {
                "name": "macOS 15 Arm",
                "os": "macos-15",
                "cc": "clang",
                "cxx": "clang++",
                "fort": "gfortran",
                "coverage": false
              },
              {
                "name": "macOS 15 Intel",
                "os": "macos-15-intel",
                "cc": "clang",
                "cxx": "clang++",
                "fort": "gfortran",
                "coverage": false
              }
            ]
          } 
